VITE_SUPABASE_URL=https://vbmxpdmoozfovqpcekzw.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibXhwZG1vb3pmb3ZxcGNla3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NDYxMTMsImV4cCI6MjA3NzUyMjExM30.MdhYptvrfsuiMEewKYv13lIrJnwrqeigouCc9gXiMtw
